version: '2'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=stock_exchange
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data-volume:/var/lib/postgresql/data
  backend:
    build: .
#    command: /code/initserver.sh
#    volumes:
#      - ./:/app
    ports:
      - "12345:12345"
    depends_on:
      - db

#
volumes:
  data-volume: